### ISSUE TITLE
[Blockbook] mainnet-explorer.wakiyamap.dev out-of-sync, stuck on block 761248

### ISSUE THREAD

**Issue by greatwolf** [wakiyamap/wakiyamap#1]
Just wanted to raise a quick issue. mainnet-explorer.wakiyamap.dev is currently out of sync with the main bitcoin blockchain. It is currently stuck on block `761248`.

Upstream is already aware of the problem and fixed here: https://github.com/trezor/blockbook/issues/820

You should update the fix to get the explorer working again.

**Comment by wakiyamap** [comment]
I'm sorry. This is a server that I personally build. I will fix it soon. Please close. Since there is a trezor issue.

**Comment by wakiyamap** [comment]
I will contact you when it is fixed. It's being built now.

**Comment by wakiyamap** [comment]
The db was corrupted and it takes a long time to resync. thank you for teaching me!

**Comment by wakiyamap** [comment]
@greatwolf Thanks!!
